name: ci-workflows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: "Run linters"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19'
          check-latest: true
      - uses: golangci/golangci-lint-action@v3

  test:
    name: 'Run test-cases'
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19'
          check-latest: true
      - run: make test

  coverage:
    name: 'Run codecov'
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19'
          check-latest: true
      - run: make cover
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          verbose: true
